name: Release

on: 
  release:
    types:
      - published

jobs:
  release-linux:
    permissions: write-all
    name: Linux release
    runs-on: ubuntu-22.04
    container:
      image: swift:5.7.3-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          apt-get update -y
          apt-get install zip
          apt-get install gh -y
          swift build -c release
          cp ./.build/release/figma-export ./Release/figma-export
          cp -r ./.build/release/figma-export_AndroidExport.resources ./Release/figma-export_AndroidExport.resources
          zip -r figma-export-linux.zip Release LICENSE

      - name: "Upload assets to a release"
        run: |
          apt-get update -y
          apt-get install gh -y
          git config --global safe.directory '*'
          gh release upload ${{ github.event.release.tag_name }} figma-export-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
